### ISSUE TITLE
Computercraft turtle mining logs near player gives the player trinkets

### ISSUE THREAD

**Issue by Goldenlion5648** [owmii/Lost-Trinkets#21]
I wrote a computercraft mining turtle program to mine logs, and just standing near it gives me trinkets while the turtle mines.

**Comment by BlueAgent** [comment]
Seems like the reason why this is happening is that CC:Tweaked [uses the owner's UUID for their fake player](https://github.com/SquidDev-CC/CC-Tweaked/blob/c5694ea9661c7a40021ebd280c378bd7bdc56988/src/main/java/dan200/computercraft/shared/turtle/core/TurtlePlayer.java#L53-L55).
This can probably be fixed by filtering out `instanceof FakePlayer`.
